import About from './component/about/About'
import Carousel from './component/carousel/Carousel'
import Footer from './component/footer/Footer'
import Insta from './component/instagram/Insta'
import Navbar from './component/nav/navbar'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Carousel />
        
        {children}
        <About />
        
        <Insta />
        <Footer />
        </body>
    </html>
  )
}
